name: dart_chat_common
description: Chat for Dart - Common part.
version: 0.1.0
author: SteÌphane Este-Gracias <sestegra@gmail.com>
publish_to: none

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  json_serializable: ^0.2.3
  http: ^0.11.3+14
  logging: ^0.11.3+1
  logging_handlers: ^0.8.0

dev_dependencies:
  build_runner: ^0.4.0+3
  test: ^0.12.0
